### ISSUE TITLE
Async explosions (creepers) causes async tracker update?

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#153]
`[12:58:15] [pool-2-thread-2/WARN]: java.lang.IllegalStateException: Asynchronous entity track!

[12:58:15] [pool-2-thread-2/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:13)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:104)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:68)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.World.a(World.java:1360)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1033)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1353)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1269)

[12:58:15] [pool-2-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItem(CraftWorld.java:340)

[12:58:15] [pool-2-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItemNaturally(CraftWorld.java:379)

[12:58:15] [pool-2-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:387)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:904)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityCreeper.die(EntityCreeper.java:137)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:840)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:43)

[12:58:15] [pool-2-thread-2/WARN]: 	at net.minecraft.server.v1_8_R3.Explosion.lambda$0(Explosion.java:154)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

[12:58:15] [pool-2-thread-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
`

**Comment by Lucaskyy** [comment]
Oh, that's weird.. That shouldn't even happen, since TNT is NOT async. Only the calculations are.

**Comment by Lucaskyy** [comment]
Oh, I found the issue. I made a mistake when writing it, damaging entities from TNT is actually done async.. Oops.

**Comment by CyberFlameGO** [comment]
Make sure to link this issue to the pull request if/when you make one to fix this

**Comment by CyberFlameGO** [comment]
@Lucaskyy was this fixed?
