### ISSUE TITLE
Server not launching:  java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by zwrumpy** [CobbleSword/NachoSpigot#201]
**Server:**
Java 8
Latest Nachospigot

**Server Error Log:**
java.lang.UnsatisfiedLinkError: 
Could not load library. Reasons: [no jansi64-git-NachoSpigot-"b6bc177" in java.library.path, no jansi-git-NachoSpigot-"b6bc177" in java.library.path, no jansi in java.library.path, The filename, directory name, or volume label syntax is incorrect]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
        at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at org.bukkit.craftbukkit.Main.main(Main.java:191)

**Comment by CyberFlameGO** [comment]
A temporary workaround is to use the -nojline startup flag, but we're aware of the issue
