### ISSUE TITLE
Citizens patch fails due to an illegal reflective access operation on Java 16+

### ISSUE THREAD

**Issue by Elierrr** [CobbleSword/NachoSpigot#211]
On versions before Java 11, the Citizens patch would succeed.

On Java versions 11-15, the Citizens patch would succeed with a warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bukkit.craftbukkit.libs.javassist.util.proxy.SecurityActions (file:/data/Servers/NachoTest/NachoSpigot.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.bukkit.craftbukkit.libs.javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
On Java 16 and later, the Citizens patch fails on:
```
[19:22:09 WARN]: Could not patch Citizens.
[19:22:09 WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1ea0fbbc
[19:22:09 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[19:22:09 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[19:22:09 WARN]:        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[19:22:09 WARN]:        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.ClassPool.toClass(ClassPool.java:1240)
[19:22:09 WARN]:        at org.bukkit.craftbukkit.libs.javassist.CtClass.toClass(CtClass.java:1392)
[19:22:09 WARN]:        at xyz.sculas.nacho.patches.RuntimePatches.lambda$applyCitizensPatch$1(RuntimePatches.java:131)
[19:22:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:22:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
This can be bypassed with the `--illegal-access=permit` JVM argument in Java 16, however this is removed in Java 17.
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
```

**Comment by Lambsy** [comment]
Adding the startup flag `--add-opens java.base/java.lang=ALL-UNNAMED` could be a temporary fix.

**Comment by Lucaskyy** [comment]
Yeah.. this is a pain in the butt. I'll have to take a look sometime.

**Comment by Lucaskyy** [comment]
Citizens patch is going to be removed pretty soon anyway.

**Comment by CyberFlameGO** [comment]
An actual fix seems to be to use the Unsafe class, from looking around.
