### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by xIsm4** [CobbleSword/NachoSpigot#218]
Actually, from last yaml config patch, it won't compile, and isn't only me.

**Comment by Elierrr** [comment]
The CI compiles fine, are you compiling from the server directory?

**Comment by xIsm4** [comment]
Yeah, also isn't only me.

**Comment by Elierrr** [comment]
Works fine for me, what error are you getting?

**Comment by xIsm4** [comment]
-
Loading NachoSpigot config from nacho.yml
Loading NachoSpigot config from nacho.yml
Loading NachoSpigot config from nacho.yml
Loading NachoSpigot config from nacho.yml
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.297 s <<< FAILURE! - in me.elier.nachospigot.config.ConfigurationTests
[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig  Time elapsed: 0.161 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig(ConfigurationTests.java:33)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.loadConfig  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.loadConfig(ConfigurationTests.java:38)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig(ConfigurationTests.java:26)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig  Time elapsed: 0.017 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig(ConfigurationTests.java:16)

**Comment by Elierrr** [comment]
Can you run it with `-DtrimStackTrace=false`?

**Comment by xIsm4** [comment]
I tried that yesterday, and same.

**Comment by Elierrr** [comment]
I need that argument to see the full error because it's true by default

**Comment by xIsm4** [comment]
I just did it again, this it's the build failure:


        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NullPointerException
        at org.bukkit.Bukkit.getLogger(Bukkit.java:611)
        at me.elier.nachospigot.config.NachoConfig.migrate(NachoConfig.java:64)
        at me.elier.nachospigot.config.NachoConfig.init(NachoConfig.java:49)
        at me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig(ConfigurationTests.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

**Comment by Elierrr** [comment]
Try deleting NachoSpigot-Server/target and then building again

**Comment by xIsm4** [comment]
> Try deleting NachoSpigot-Server/target and then building again

Same;:

Loading NachoSpigot config from nacho.yml
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.408 s <<< FAILURE! - in me.elier.nachospigot.config.ConfigurationTests
[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig  Time elapsed: 0.27 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig(ConfigurationTests.java:33)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.loadConfig  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.loadConfig(ConfigurationTests.java:38)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig(ConfigurationTests.java:26)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig  Time elapsed: 0.026 s  <<< ERROR!
java.lang.NullPointerException
        at me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig(ConfigurationTests.java:16)

**Comment by Elierrr** [comment]
It's failing to delete the nacho.json file, do you know anything that could cause it to fail to delete?

**Comment by andreasdc** [comment]
> It's failing to delete the nacho.json file, do you know anything that could cause it to fail to delete?

no permissions?

**Comment by Elierrr** [comment]
> > It's failing to delete the nacho.json file, do you know anything that could cause it to fail to delete?
> 
> no permissions?

Wouldn't make sense since the file was just made

**Comment by andreasdc** [comment]
> e

it does make sense to me

**Comment by Elierrr** [comment]
Try compiling with my PR so that we can see the actual error (as the only errors we are getting are Logger errors)
`git fetch origin pull/219/head:compile-issue`
`git checkout compile-issue`

**Comment by xIsm4** [comment]
Okay, so i did it and seems like the process it's beeing used already


[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.95 s <<< FAILURE! - in me.elier.nachospigot.config.ConfigurationTests
[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig  Time elapsed: 0.608 s  <<< ERROR!
java.lang.RuntimeException:
java.nio.file.FileSystemException: nacho.json: 
The process does not have access to the file because it is being used by another process.

        at me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig(ConfigurationTests.java:37)
Caused by: java.nio.file.FileSystemException:
nacho.json: 
The process does not have access to the file because it is being used by another process.

        at me.elier.nachospigot.config.ConfigurationTests.migrateEmptyConfig(ConfigurationTests.java:37)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.loadConfig  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException:
java.nio.file.FileSystemException: nacho.json: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

        at me.elier.nachospigot.config.ConfigurationTests.loadConfig(ConfigurationTests.java:43)
Caused by: java.nio.file.FileSystemException:
nacho.json: 
The process does not have access to the file because it is being used by another process.

        at me.elier.nachospigot.config.ConfigurationTests.loadConfig(ConfigurationTests.java:43)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig  Time elapsed: 0.023 s  <<< ERROR!
java.lang.RuntimeException:
java.nio.file.FileSystemException: nacho.json: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

        at me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig(ConfigurationTests.java:29)
Caused by: java.nio.file.FileSystemException:
nacho.json: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

        at me.elier.nachospigot.config.ConfigurationTests.migratePartialModifiedConfig(ConfigurationTests.java:29)

[ERROR] me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException:
java.nio.file.FileSystemException: nacho.json: 
The process does not have access to the file because it is being used by another process.

        at me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig(ConfigurationTests.java:18)
Caused by: java.nio.file.FileSystemException:
nacho.json:
The process does not have access to the file because it is being used by another process.

        at me.elier.nachospigot.config.ConfigurationTests.migrateFullConfig(ConfigurationTests.java:18)

**Comment by xIsm4** [comment]
So what's the solution?
