### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#241]
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.DamageSource.ignoresInvulnerability()" because "var2" is null
	at net.minecraft.server.v1_8_R3.EnchantmentProtection.a(EnchantmentProtection.java:41) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EnchantmentManager$EnchantmentModifierProtection.a(EnchantmentManager.java:436) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EnchantmentManager.a(EnchantmentManager.java:107) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EnchantmentManager.a(EnchantmentManager.java:122) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EnchantmentManager.a(EnchantmentManager.java:130) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.applyMagicModifier(EntityLiving.java:1082) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving$5.apply(EntityLiving.java:1156) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving$5.apply(EntityLiving.java:1) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1159) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:905) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:769) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:844) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:617) ~[nachospigot.jar:?]
	at net.minecraft.server.v1_8_R3.Explosion.lambda$1(Explosion.java:157) ~[nachospigot.jar:?]

**Comment by Lucaskyy** [comment]
Hmm? What was this all about?

**Comment by andreasdc** [comment]
> Hmm? What was this all about?

My mistake
