### ISSUE TITLE
Log4j update breaks luckperms

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#285]
### Observed Behavior

The commit https://github.com/CobbleSword/NachoSpigot/commit/5e428c973f4083a06dc519d5d9568597f5927943 breaks Luckperms, aswell as many other plugins relying on slf4j.
```
[10.12 12:54:54.021] INFO: [Lobby-1] [12:54:53 INFO]: [LuckPerms] Enabling LuckPerms v5.3.88
[10.12 12:54:54.021] INFO: [Lobby-1] [12:54:53 INFO]:         __
[10.12 12:54:54.021] INFO: [Lobby-1] [12:54:53 INFO]:   |    |__)   LuckPerms v5.3.88
[10.12 12:54:54.021] INFO: [Lobby-1] [12:54:53 INFO]:   |___ |      Running on Bukkit - NachoSpigot
[10.12 12:54:54.021] INFO: [Lobby-1] [12:54:53 INFO]: [LuckPerms] Loading configuration...
[10.12 12:54:55.021] INFO: [Lobby-1] [12:54:54 INFO]: [LuckPerms] Loading storage provider... [MONGODB]
[10.12 12:54:55.021] INFO: [Lobby-1] [12:54:54 ERROR]: Error occurred while enabling LuckPerms v5.3.88 (Is it up to date?)
[10.12 12:54:55.021] INFO: [Lobby-1] java.lang.NoSuchMethodError: 'boolean org.apache.logging.log4j.spi.LoggerContextFactory.isClassLoaderDependent()'
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:49) ~[paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33) ~[paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.diagnostics.logging.SLF4JLogger.<init>(SLF4JLogger.java:26) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.diagnostics.logging.Loggers.getLogger(Loggers.java:50) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.internal.connection.BaseCluster.<clinit>(BaseCluster.java:68) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.connection.DefaultClusterFactory.createCluster(DefaultClusterFactory.java:192) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.Mongo.createCluster(Mongo.java:753) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.Mongo.createCluster(Mongo.java:745) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.Mongo.<init>(Mongo.java:298) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.Mongo.<init>(Mongo.java:293) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.lib.mongodb.MongoClient.<init>(MongoClient.java:210) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.init(MongoStorage.java:133) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:166) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[?:?]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:390) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:349) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:208) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [paper.jar:git-NachoSpigot-"77b3066"]
[10.12 12:54:55.021] INFO: [Lobby-1]  at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
[10.12 12:54:55.021] INFO: [Lobby-1] [12:54:54 INFO]: [LuckPerms] Disabling LuckPerms v5.3.88
```

### Expected Behavior

To not break plugins

### Steps To Reproduce

Install luckperms and launch server

### Plugin List

Luckperms
Also anything else using slf4j is not working.

### Server Version

commit 77b3066

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by CyberFlameGO** [comment]
Thanks for making this issue! We’re aware of this, and as far as I’m aware @Lucaskyy is working on a fix

**Comment by Sneakometer** [comment]
Also, the log4j vulnerability is NOT fixed in latest nacho builds.

**Comment by CyberFlameGO** [comment]
We’re also aware of this, #284 is pending a merge

**Comment by Elierrr** [comment]
I have a fix for this in [my branch](https://github.com/Elierrr/NachoSpigot/tree/fix/slf4j) however I haven't been able to test it yet.
