### ISSUE TITLE
ReportedException: Colliding entity with block

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#297]
### Observed Behavior

```
[21:51:04] [Server thread/WARN]: Entity threw exception at SKonsole:6.2890383938737315,72.0,-6.007075360277029
[21:51:04] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:508)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityFireworks.t_(EntityFireworks.java:59)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1886)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1853)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1679)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:865)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:405)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619)
[21:51:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:51:04] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraft.server.v1_8_R3.IBlockData.get(net.minecraft.server.v1_8_R3.IBlockState)" is null
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:20)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.f(BlockPressurePlateBinary.java:51)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:100)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:93)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:890)
[21:51:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:502)
[21:51:04] [Server thread/WARN]: 	... 10 more
```

### Expected Behavior

No exceptions in log

### Steps To Reproduce

Not sure, happens seemingly random.

### Plugin List

MultiverseCore
Custom stuff

### Server Version

9fef576

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by LewUwU** [comment]
Can you try to reproduce this on a clean PaperSpigot server?

**Comment by Lucaskyy** [comment]
Seems like it tries to get the block data of a block that doesn't exist.
...
...what?

**Comment by Sneakometer** [comment]
> Can you try to reproduce this on a clean PaperSpigot server?

Not sure how. I don't even know what causes it.
I opened the issue hoping someone knows what could cause it or point me in the right direction.

**Comment by Lucaskyy** [comment]
The only way to know what's wrong is by looking at the code in the stack trace, sadly I cannot do that right now. So if someone else wants to look, feel free.

**Comment by Sneakometer** [comment]
Just found a new variant of this error: ```
[21:28:24] [Server thread/WARN]: Entity threw exception at SPizza:-3.7232727385446003,13.0,-15.376457824959989
[21:28:24] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:508)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:83)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1887)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1854)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1678)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:865)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619)
[21:28:24] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:28:24] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraft.server.v1_8_R3.IBlockData.get(net.minecraft.server.v1_8_R3.IBlockState)" is null
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:20)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.f(BlockPressurePlateBinary.java:51)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:100)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:93)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:890)
[21:28:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:502)
[21:28:24] [Server thread/WARN]: 	... 10 more
```

**Comment by Elierrr** [comment]
Do your plugins do anything related to Item/Firework/Arrow entities? If so then they may be causing the issue.

**Comment by HowardZHY** [comment]
I remember this could happen on Taco and TorchSpigot , when a zombie or skeleton bumped into cactus and got damaged , there's an error like this.

**Comment by Sneakometer** [comment]
> Do your plugins do anything related to Item/Firework/Arrow entities? If so then they may be causing the issue.

No, i don't think so. Only thing that i could think of is some semi illegal asynchronous api usage (read only) in our anticheat.
I'm gonna test if the issue persists without the AC.

**Comment by Sneakometer** [comment]
> I couldnt reproduce it on latest build [706108e](https://github.com/CobbleSword/NachoSpigot/commit/706108eac45401ee5091c781a842ada7bf152631) with multiversecore. I dropped zombies + items on diverse pressure plates and cactus. Nothing in log. Probably wanna try if it still happens @Sneakometer

Issue still persists in adae067d558ddeef0c4aa0d8755548370e5da6f4

```
[17:58:41] [Server thread/WARN]: Entity threw exception at SBoxingRing:-19.29391259787141,15.0,-20.20898492488268
[17:58:41] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:511)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:83)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1887)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1854)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1678)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617)
[17:58:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:58:41] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "net.minecraft.server.v1_8_R3.IBlockData.get(net.minecraft.server.v1_8_R3.IBlockState)" is null
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:20)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.f(BlockPressurePlateBinary.java:51)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:100)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:93)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:893)
[17:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:505)
[17:58:41] [Server thread/WARN]: 	... 10 more
```
