### ISSUE TITLE
ProtocolLib Unable to find NetworkManager

### ISSUE THREAD

**Issue by caoli5288** [CobbleSword/NachoSpigot#328]
### Observed Behavior

```
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x1f9ff307, L:/10.200.68.106:41802 - R:/10.200.71.72:55849]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:155)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:169)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

### Expected Behavior

Just work

### Steps To Reproduce

Just start server

### Plugin List

- ProtocolLib
- ViaVersion

### Server Version

This server is running NachoSpigot version git-NachoSpigot-"c901193" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by sadcenter** [comment]
Do players join from the higher versions? Also, are you using the latest version of ProtocolLib?
I reproduced the steps and didn't get errors, maybe that's a compatibility issue with ViaVersion

**Comment by caoli5288** [comment]
@sadcenter openjdk-11 with newest ProtocolLib and ViaVersion. Client version is forge-1.12.2

**Comment by Lucaskyy** [comment]
@caoli5288 Make sure in `nacho.yml` that the ProtocolLib shim is turned on. If it's not, then it obviously won't work with ProtocolLib.

**Comment by Elierrr** [comment]
I cannot reproduce this with the information you provided on Linux and Windows.

> Make sure in `nacho.yml` that the ProtocolLib shim is turned on. If it's not, then it obviously won't work with ProtocolLib.

It is not caused by this because it would produce a different error.

**Comment by caoli5288** [comment]
Resolved after I update ViaVersion to newest version. THX.
