### ISSUE TITLE
Error thown with Citizens

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/NachoSpigot#342]
### Observed Behavior

I didn't find abnormal behavior in game , but console throwed error.
[19:01:46] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:141) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:64) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.World.a(World.java:1298) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1002) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.World.b(World.java:3041) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:985) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:162) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:150) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:96) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:624) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.Location.getBlock(Location.java:87) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.citizensnpcs.nms.v1_8_R3.entity.MobEntityController.createEntity(MobEntityController.java:35) [Citizens-2.0.29-b2434.jar:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) [Citizens-2.0.29-b2434.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:255) [Citizens-2.0.29-b2434.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:160) [Citizens-2.0.29-b2434.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens-2.0.29-b2434.jar:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) [Citizens-2.0.29-b2434.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:793) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	... 30 more

### Expected Behavior

No error

### Steps To Reproduce

Use plugin Citizens and Sentinel.
Create a npc and restart the server, error will be shown on console.

### Plugin List

[19:02:11] [Server thread/INFO]: Plugins (31): [0;32;1mWarpMagic[0;37;1m, [0;32;1mCorpseReborn[0;37;1m, [0;32;1mPermissionsDisable[0;37;1m, [0;32;1mBleed[0;37;1m, [0;32;1mClearLag[0;37;1m, [0;32;1mCrackShot[0;37;1m, [0;32;1mCrazyCore[0;37;1m, [0;32;1mChairs[0;37;1m, [0;32;1mCitizens[0;37;1m, [0;32;1mLANBroadcaster[0;37;1m, [0;32;1mSentinel[0;37;1m, [0;32;1mAntiCmds[0;37;1m, [0;32;1mResidence[0;37;1m, [0;32;1mBetterPing[0;37;1m, [0;32;1mUnBreakable[0;37;1m, [0;32;1mCS-CoreLib[0;37;1m, [0;32;1mMiaoLog4j2Fix[0;37;1m, [0;32;1mProtocolSupport[0;37;1m, [0;32;1mSimpleSit[0;37;1m, [0;32;1mCrazyLoginFilter[0;37;1m, [0;32;1mSlimefun[0;37;1m, [0;32;1mViaVersion[0;37;1m, [0;32;1mViaRewind[0;37;1m, [0;32;1mViaVersionStatus[0;37;1m, [0;32;1mProtocolLib[0;37;1m, [0;32;1mSkinsRestorer[0;37;1m, [0;32;1mBlessingSkinSync[0;37;1m, [0;32;1mBKCommonLib[0;37;1m, [0;32;1mClientStats[0;37;1m, [0;32;1mColorMOTD[0;37;1m, [0;32;1mTrain_Carts[m

### Server Version

NachoSpigot version git-NachoSpigot-"f5de3b6" (MC: 1.8.8)

### Other

[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7970282/latest.log)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by LewUwU** [comment]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"f5de3b6"]
	... 30 more
	
	Seems to be more a Citizens issue, but i can do a 'fix'

**Comment by HowardZHY** [comment]
No error on Burrito, but on Nacho.

**Comment by HowardZHY** [comment]
Not fixed yet
[14:00:35] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:141) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:64) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.World.a(World.java:1298) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1002) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.World.b(World.java:3041) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:985) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:162) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:150) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:96) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:624) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.Location.getBlock(Location.java:87) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.citizensnpcs.nms.v1_8_R3.entity.MobEntityController.createEntity(MobEntityController.java:34) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:255) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:160) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) [Citizens-2.0.29-b2462.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:793) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"70cd4ae"]
	... 30 more

**Comment by HowardZHY** [comment]
still on latest version

**Comment by HowardZHY** [comment]
I wonder when to fix it

**Comment by HowardZHY** [comment]
I report this on Citizens issues now

**Comment by HowardZHY** [comment]
[11:52:00] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:141) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:64) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.World.a(World.java:1298) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1002) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.World.b(World.java:3041) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:985) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:35) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:805) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617) [NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"9c02430"]
	... 16 more

**Comment by HowardZHY** [comment]
[01:40:46 ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
        at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:141) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:64) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.World.a(World.java:1298) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1002) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.World.b(World.java:3042) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:987) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:162) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:150) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:96) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:624) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.Location.getBlock(Location.java:87) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.citizensnpcs.nms.v1_8_R3.entity.MobEntityController.createEntity(MobEntityController.java:34) [Citizens-2.0.29-b2462.jar:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) [Citizens-2.0.29-b2462.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:255) [Citizens-2.0.29-b2462.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:160) [Citizens-2.0.29-b2462.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens-2.0.29-b2462.jar:?]
        at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) [Citizens-2.0.29-b2462.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:795) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617) [NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"86fb06b"]
        ... 30 more
