### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by caoli5288** [CobbleSword/NachoSpigot#401]
### Observed Behavior

Server crash

### Expected Behavior

Server alive

### Steps To Reproduce

Unknown

### Server Version

NachoSpigot version git-NachoSpigot-"74ed0ea" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Other

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 4/6/22, 3:58 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:589)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:405)
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:230)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	at java.base/java.lang.Thread.run(Thread.java:829)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:589)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:405)
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:230)

-- Affected level --
Details:
	Level name: ASkyBlock
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 75 Drop: 0
	Level seed: 2066246926961661482
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: 0.00,127.00,0.00 - World: (0,127,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1608606419 game time, 1608780918 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 77854 (now: false), thunder time: 100903 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	at java.base/java.lang.Thread.run(Thread.java:829)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 11.0.12, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 4414504960 bytes (4210 MB) / 17179869184 bytes (16384 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xlog:gc -Xmx16G -Xms3072M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: NachoSpigot version git-NachoSpigot-"74ed0ea" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) false
```

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by crafter23456** [comment]
https://github.com/crafter23456/NachoSpigot/actions/runs/2098430011
try that. it might fix it. please tell if its working and I'll do a PR

**Comment by EzJamo** [comment]
Had the same issue.

**Comment by Elierrr** [comment]
Duplicate of #398
