### ISSUE TITLE
Plugin dosent work on NachoSPigot

### ISSUE THREAD

**Issue by BakuQ** [CobbleSword/NachoSpigot#404]
### Observed Behavior

[11:34:05] [Craft Scheduler Thread - 1/INFO]: Checksum of file: /home/main/plugins/safemc.jar is: c66b97812252e9c7db8a09af65455db2
[11:34:05] [Craft Scheduler Thread - 1/WARN]: [SafeMC-Launcher] Cannot launch application! null
[11:34:05] [Craft Scheduler Thread - 1/WARN]: java.lang.NullPointerException
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at me.hp888.launcher.Launcher.launchApp(Launcher.java:130)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at me.hp888.launcher.Bootstrap.lambda$onEnable$0(Bootstrap.java:32)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:34:05] [Craft Scheduler Thread - 1/WARN]: 	at java.lang.Thread.run(Thread.java:748)

### Expected Behavior

The plugin does not work on nachospigot

### Steps To Reproduce

I don't know myself

### Server Version

1.8.8

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by LewUwU** [comment]
What is SafeMC?

**Comment by BakuQ** [comment]
> What is SafeMC?

AntiCrash plugin

**Comment by LewUwU** [comment]
Does that plugin work on PaperSpigot?

**Comment by BakuQ** [comment]
> Does that plugin work on PaperSpigot?

Yes, work

**Comment by BakuQ** [comment]
On the older version of NachoSPigot, this plugin worked
