### ISSUE TITLE
seemingly random ReportedException

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#47]
Spotted this exception multiple times in my server log and just wanted to share it with you.
I'm not sure how to trigger this, may be related to some redstone fixes?
```
java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_291]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_291]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [paper.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [paper.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409) [paper.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:718) [paper.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615) [paper.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block
	at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:385) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:416) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[paper.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_291]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[paper.jar:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:20) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.BlockPressurePlateBinary.f(BlockPressurePlateBinary.java:51) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:100) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:93) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:891) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:499) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.g(EntityLiving.java:1418) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityHuman.g(EntityHuman.java:1371) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1671) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityHuman.m(EntityHuman.java:395) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1511) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:175) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:320) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:416) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[paper.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[paper.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_291]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[paper.jar:?]
	... 5 more
```
Java 8 
latest commit

**Comment by Lucaskyy** [comment]
@LewUwU Do you have any idea why this happens?

**Comment by LewUwU** [comment]
Maybe could be done by the patch done by @HeathLoganCampbell a lot of time ago (Use less resource for collision)

as the exception says this: 'java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R3.ReportedException: Colliding entity with block'

**Comment by Lucaskyy** [comment]
Could be yeah, only thing is.. no clue how to reproduce it. The error tells me something about pressure plates, haven't tested them yet.

@Sneakometer Could you provide us your plugin list here or in DMs?

**Comment by Sneakometer** [comment]
Plugin list: ViaVersion, Multiverse-Core, Luckperms
The server is also running a bunch of self made plugins, but i don't suspect the problem in any of them as they don't tinker with entity collision nor pressure plates.

**Comment by HeathLoganCampbell** [comment]
This seems to be a bug related to https://bugs.mojang.com/browse/MC-156111 try clearing all items
