### ISSUE TITLE
Spawner bug

### ISSUE THREAD

**Issue by benfiratkaya** [CobbleSword/NachoSpigot#49]
Hello we was using paper and we move to nachospigot. But we have a problem with spawners.
This bug coming with nacho. We try with paper not works.

Video:
https://streamable.com/gavnst

**Comment by Lucaskyy** [comment]
Can you provide us the plugin you were using so we can reproduce this locally? And does this _**only**_ happen with NachoSpigot or does this also happen with other forks like Spigot or Paper?

**Comment by benfiratkaya** [comment]
Only Nacho and I try with zero plugin server. Bug still hapening :(

**Comment by Lucaskyy** [comment]
Oh, this has nothing to do with plugins?
So this is purely an issue with mob spawners in general?

**Comment by benfiratkaya** [comment]
We are trying with CMI spawner system and we see this bug. And we disable CMI spawner system and trying with WildStacker spawner system we see this bug again. This bug working with NachoSpigot. We try with Paper but we didn't see any problem.
My idea: Spawner plugins and nacho spigot can't synchronize and spawner events conflict with each other.

**Comment by benfiratkaya** [comment]
wildstacker errors. We get these errors only working with nachospigot
We get the error when despite breaking the spawner, the mobs continue to spawn.
```
[15:35:36] [Server thread/ERROR]: Could not pass event SpawnerSpawnEvent to WildStacker v3.5.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[NachoSpigot.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[NachoSpigot.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[NachoSpigot.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:490) [NachoSpigot.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:475) [NachoSpigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callSpawnerSpawnEvent(CraftEventFactory.java:144) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.MobSpawnerAbstract.a(MobSpawnerAbstract.java:217) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.MobSpawnerAbstract.c(MobSpawnerAbstract.java:129) [NachoSpigot.jar:?]
	at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_8_R3$StackedMobSpawner.c(NMSSpawners_v1_8_R3.java:303) [WildStacker-3.5.2.jar:?]
	at net.minecraft.server.v1_8_R3.TileEntityMobSpawner.c(SourceFile:55) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1731) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:598) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:859) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:718) [NachoSpigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615) [NachoSpigot.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by Outfluencer** [comment]
Seams like Natcho is firering a Spawner Spawn event with a null creature spawner

**Comment by benfiratkaya** [comment]
https://github.com/BG-Software-LLC/WildStacker

**Comment by benfiratkaya** [comment]
Any idea?

**Comment by Lucaskyy** [comment]
@benfiratkaya It should be fixed in the latest version! Could you please try again? :) Reopen this issue if it still occurs.
