### ISSUE TITLE
ViaVersion 4.0.0 support

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#60]
Hey, 
ViaVersion updated their API in the latest version 4.0.0 andNachoSpigot now fails to patch the block placement.
You can find all changes made to the api here: https://gist.github.com/KennyTV/3778685985ddc45bd99e003191ff02eb

Here the exception printed on startup:
```
[04:07:12] [Server thread/WARN]: Could not patch block placement.
[04:07:12] [Server thread/WARN]: java.lang.NoSuchMethodException: us.myles.ViaVersion.api.Via.getManager()
[04:07:12] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2195)
[04:07:12] [Server thread/WARN]: 	at dev.cobblesword.nachospigot.patches.RuntimePatches.applyViaVersionBlockPatch(RuntimePatches.java:32)
[04:07:12] [Server thread/WARN]: 	at dev.cobblesword.nachospigot.Nacho.applyPatches(Nacho.java:69)
[04:07:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:343)
[04:07:12] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[04:07:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Lucaskyy** [comment]
I saw it, I will fix it when I'm home.

**Comment by CyberFlameGO** [comment]
Link this issue to pull #66 maybe?
