### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#79]
java.lang.NullPointerException: Exception in server tick loop
	at it.unimi.dsi.fastutil.objects.Reference2BooleanOpenHashMap$MapIterator.nextEntry(Reference2BooleanOpenHashMap.java:674)
	at it.unimi.dsi.fastutil.objects.Reference2BooleanOpenHashMap$KeyIterator.next(Reference2BooleanOpenHashMap.java:900)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:326)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:334)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:300)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:226)
	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:212)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:964)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:769)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:658)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by LewUwU** [comment]
Send full stack trace

**Comment by andreasdc** [comment]
> Send full stack trace

what do you need from it?

**Comment by CyberFlameGO** [comment]
This information isn't enough so I think @LewUwU needs some context, and the plugins you're using

**Comment by bob7l** [comment]
Usually you'll get a nullpointer from FastUtil collections/maps if you use them among multiple threads without proper thread safety. So it's either that, or somebody made a mistake somewhere

**Comment by andreasdc** [comment]
@bob7l I fixed it but adding back async catchers in EntityTrackerEntry, but how would they been used on multiple threads?

**Comment by bob7l** [comment]
> 
> 
> @bob7l I fixed it but adding back async catchers in EntityTrackerEntry, but how would they been used on multiple threads?

I don't know whether you're using that object among multiple threads, just noting that if you ARE, that error is likely a product of it.

**Comment by andreasdc** [comment]
> > @bob7l I fixed it but adding back async catchers in EntityTrackerEntry, but how would they been used on multiple threads?
> 
> I don't know whether you're using that object among multiple threads, just noting that if you ARE, that error is likely a product of it.

Specifically i don't use this class nowhere, how else?
