### ISSUE TITLE
Nacho + nAntiBot problem

### ISSUE THREAD

**Issue by SOekd** [CobbleSword/NachoSpigot#80]
nAntiBot download: https://www.nickuc.com/pt/details/nantibot 

This only happens using NachoSpigot.

Exception:
[17:21:08 WARN]: java.util.NoSuchElementException: timeout
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290)
[17:21:08 WARN]:        at com.nickuc.antibot.╬®╬©╬ö¤å¤ç╬┤¤ü╬║¤â╬╗╬ô.a(├ñTmPFbCNdFuiHxfNrMP0S4Tlwbjsw1mDa6kX1ITvomb7FdKVbw8mbvqqj9l7Em9vrxaGmxyui9K7UMrBfxpT6vOGkDbH/lajuIQ==11├ÂSKQYe├ÂFkJRVsXImh1Sypm70o=6├ÂMyxHc├ÂFdoCHtO/sx+KdM+cgFCT2KB2GoQ==4├ÂDXXYS├ÂFsXmNFi8FTBrdzm27E=6├ÂUBCMA├ÂÓáúÓáçÓáÄÓáëÓá®▀▓ÓáìÓáöÓáÁÓá½▀ÁÓáöÓáûÓáÜÓáÄÓáïÓáÇÓáÿÓáñÓáöÓá×ÓááÓáìÓáÄ├ÂUfjpt├ÂTsdysHkwdVyHCyQWFke6koL7upfh87tKkivQ==13├ÂuEOiM├ÂþùÇþùëþû┤þùúþÿÇþùáþû¥þùÖþÿàþùÂþùÆþùÜþùøþùªþù£þù¡þÿìþÿîþÿâþùøþù¢þù¡þùÜþùø├ÂUnQVK├ÂÝîøÝî£ÝîâÝî¿Ýï░ÝîªÝîƒÝïÁÝî¼ÝîÅÝîöÝîûÝîëÝî▓ÝîÜÝîÜÝîÅÝîÂÝîÀÝî¼ÝîéÝî£ÝîëÝîè├ÂShByB├ÂõºÇõºÑõº¢õºªõº¢õºªõºîõºáõº¡õº©õº©õ¿Åõº¡õºªõ¿éõº▓õ¿éõºòõºÆõºÅõººõº¬õº»õº│õº×õº®õ¿ïõ¿Øõ¿Öõ¿ïõº┤õ¿ö├ÂmJpla├ÂFmsXkVZPJtA+qPJxZCOL23gQxpNbw==6├ÂqAXkx├ÂÙâ©ÙâùÙâäÙâªÙâ©ÙâÜÙâèÙâÉÙäüÙäèÙääÙâÅÙäöÙâ¥Ùâ░ÙäÆÙâÅÙâ¡ÙâñÙâ¼ÙâÅÙä£ÙâúÙâñ├ÂmVLvs├Â╠ì╠░╠á╠ó╠ñ╠Á═æ╠ô╠º╠│╠À╠£╠╝╠▓╠▒╠á╠▒╠»═å═ÿ═º═º╠À═®╠╣═é╠¥╠╝═é╠¼═▒═é├ÂfMBsm├Â├╝:328)
[17:21:08 WARN]:        at com.nickuc.antibot.╬®╬©╬ö¤å¤ç╬┤¤ü╬║¤â╬╗╬ô.a(├ñTmPFbCNdFuiHxfNrMP0S4Tlwbjsw1mDa6kX1ITvomb7FdKVbw8mbvqqj9l7Em9vrxaGmxyui9K7UMrBfxpT6vOGkDbH/lajuIQ==11├ÂSKQYe├ÂFkJRVsXImh1Sypm70o=6├ÂMyxHc├ÂFdoCHtO/sx+KdM+cgFCT2KB2GoQ==4├ÂDXXYS├ÂFsXmNFi8FTBrdzm27E=6├ÂUBCMA├ÂÓáúÓáçÓáÄÓáëÓá®▀▓ÓáìÓáöÓáÁÓá½▀ÁÓáöÓáûÓáÜÓáÄÓáïÓáÇÓáÿÓáñÓáöÓá×ÓááÓáìÓáÄ├ÂUfjpt├ÂTsdysHkwdVyHCyQWFke6koL7upfh87tKkivQ==13├ÂuEOiM├ÂþùÇþùëþû┤þùúþÿÇþùáþû¥þùÖþÿàþùÂþùÆþùÜþùøþùªþù£þù¡þÿìþÿîþÿâþùøþù¢þù¡þùÜþùø├ÂUnQVK├ÂÝîøÝî£ÝîâÝî¿Ýï░ÝîªÝîƒÝïÁÝî¼ÝîÅÝîöÝîûÝîëÝî▓ÝîÜÝîÜÝîÅÝîÂÝîÀÝî¼ÝîéÝî£ÝîëÝîè├ÂShByB├ÂõºÇõºÑõº¢õºªõº¢õºªõºîõºáõº¡õº©õº©õ¿Åõº¡õºªõ¿éõº▓õ¿éõºòõºÆõºÅõººõº¬õº»õº│õº×õº®õ¿ïõ¿Øõ¿Öõ¿ïõº┤õ¿ö├ÂmJpla├ÂFmsXkVZPJtA+qPJxZCOL23gQxpNbw==6├ÂqAXkx├ÂÙâ©ÙâùÙâäÙâªÙâ©ÙâÜÙâèÙâÉÙäüÙäèÙääÙâÅÙäöÙâ¥Ùâ░ÙäÆÙâÅÙâ¡ÙâñÙâ¼ÙâÅÙä£ÙâúÙâñ├ÂmVLvs├Â╠ì╠░╠á╠ó╠ñ╠Á═æ╠ô╠º╠│╠À╠£╠╝╠▓╠▒╠á╠▒╠»═å═ÿ═º═º╠À═®╠╣═é╠¥╠╝═é╠¼═▒═é├ÂfMBsm├Â├╝:54)
[17:21:08 WARN]:        at com.nickuc.antibot.╬ö╬┐╬ô╬║¤ë╬á╬▒╬╗╬¥¤å╬╣╬®╬©.initChannel(├ñFJH+tSIMi3C3DrrK0eOvOHDlqaRdWVwXfnIw+eWa9Lrhy1Bl+lNp1JLAA==2├ÂdAtiw├Â├╝:164)
[17:21:08 WARN]:        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[17:21:08 WARN]:        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[17:21:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
[17:21:08 WARN]:        at com.nickuc.antibot.╬▓╬Â╬Á¤ü╬À╬ú╬┐╬╗¤â╬▒╬╝.initChannel(Unknown Source)
[17:21:08 WARN]:        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[17:21:08 WARN]:        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[17:21:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[17:21:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[17:21:08 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[17:21:08 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[17:21:08 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[17:21:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:21:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:21:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:21:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:21:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:21:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:21:08 INFO]: [ERROR] [nAntiBot] Cannot inject incomming channel [id: 0x23660904, L:/127.0.0.1:25565 - R:/127.0.0.1:65292]

**Comment by LewUwU** [comment]
nAntiBot doesn't support latest netty
