### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#9]
[08:51:44 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at net.minecraft.server.v1_8_R3.RegionFile.<init>(RegionFile.java:69) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.RegionFileCache.a(RegionFileCache.java:37) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.chunkExists(ChunkRegionLoader.java:42) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:130) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:363) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:271) ~[spigot.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by CyberFlameGO** [comment]
Unsure if this is fixed or not, please respond @assasin541

**Comment by Lucaskyy** [comment]
Fixed in current commit/release.

**Closing.**
