### ISSUE TITLE
HackedServer Compatibility

### ISSUE THREAD

**Issue by Permanently** [CobbleSword/NachoSpigot#91]
I'm trying to run [HackedServer](https://www.spigotmc.org/resources/46485/) through NachoSpigot, but I'm getting this error:

```
[22:17:03 INFO]: [HackedServer] Logs file not found, creating it...
[22:17:03 ERROR]: Error occurred while enabling HackedServer v2.80.0 (Is it up to date?)
java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_8_R3.ServerConnection]).
        at io.th0rgal.hackedserver.utils.tinyprotocol.Reflection.getTypedMethod(Reflection.java:246) ~[?:?]
        at io.th0rgal.hackedserver.utils.tinyprotocol.Reflection.getMethod(Reflection.java:206) ~[?:?]
        at io.th0rgal.hackedserver.utils.tinyprotocol.Reflection.getTypedMethod(Reflection.java:244) ~[?:?]
        at io.th0rgal.hackedserver.utils.tinyprotocol.TinyProtocolFixed.<init>(TinyProtocolFixed.java:107) ~[?:?]
        at io.th0rgal.hackedserver.events.EventsManager$1.<init>(EventsManager.java:37) ~[?:?]
        at io.th0rgal.hackedserver.events.EventsManager.registerEvents(EventsManager.java:37) ~[?:?]
        at io.th0rgal.hackedserver.Core.onEnable(Core.java:90) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[nacho.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [nacho.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [nacho.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:382) [nacho.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:341) [nacho.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:405) [nacho.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:369) [nacho.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:331) [nacho.jar:?]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:296) [nacho.jar:?]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [nacho.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[22:17:03 INFO]: [HackedServer] Disabling HackedServer v2.80.0
[22:17:03 INFO]: [HackedServer] Disabled
```

Contacted the HackedServer author; they've advised me to post an issue here. Any potential fix?

**Comment by CyberFlameGO** [comment]
Hmm, looks like an NMS thing.

**Comment by LewUwU** [comment]
Netty issue

**Comment by refractored** [comment]
Isn't TinyProtocol a lightweight alternative to ProtocolLib

**Comment by Lucaskyy** [comment]
Use ProtocolLib instead of TinyProtocol.

**Comment by Permanently** [comment]
I am. That's the requirement for HackedServer.

**Comment by CyberFlameGO** [comment]
@Lucaskyy re-open this issue maybe? @Permanently has a point.


> Isn't TinyProtocol a lightweight alternative to ProtocolLib

It's a lightweight *version* of ProtocolLib. It's still very much official: https://github.com/dmulloy2/ProtocolLib/tree/master/TinyProtocol/src/main/java/com/comphenix/tinyprotocol

**Comment by LewUwU** [comment]
> @Lucaskyy re-open this issue maybe? @Permanently has a point.
> 
> > Isn't TinyProtocol a lightweight alternative to ProtocolLib
> 
> It's a lightweight _version_ of ProtocolLib. It's still very much official: https://github.com/dmulloy2/ProtocolLib/tree/master/TinyProtocol/src/main/java/com/comphenix/tinyprotocol

The issue is done due to the usage of the latest netty version, it happens on my fork too

**Comment by CyberFlameGO** [comment]
That's right, it breaks a lot of things like Citizens iirc?

**Comment by Lucaskyy** [comment]
It would mean we have to patch TinyProtocol too. I am no longer spending time on this project, so if someone else wants to go through the hassle feel free to do so.

**Comment by Lucaskyy** [comment]
This project has been abandoned for some time now, use something else. IonSpigot looks fine.
