### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#95]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at net.minecraft.server.v1_8_R3.NetworkManager.flush(NetworkManager.java:112)
	at net.minecraft.server.v1_8_R3.NetworkManager.enableAutomaticFlush(NetworkManager.java:101)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:969)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:769)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:658)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by CyberFlameGO** [comment]
What happened before this, can you show us more of the logs?

**Comment by andreasdc** [comment]
nothing special

**Comment by CyberFlameGO** [comment]
What happens before this error?

**Comment by andreasdc** [comment]
@CyberFlameGO nothing special, people playing, how could I know?

**Comment by CyberFlameGO** [comment]
Has this happened previously, and was there an error before the crash in console?

**Comment by andreasdc** [comment]
> Has this happened previously, and was there an error before the crash in console?

I saw it in the crash report

**Comment by CyberFlameGO** [comment]
Saw what in the crash report? Can you send us the crash report, and any relevant details from the console logs before the crash? Has this happened previously, and have you made any changes which could've caused these crashes to occur if so?

**Comment by BeyazPolisli** [comment]
fixed

**Comment by CyberFlameGO** [comment]
@BeyazPolisli make sure you pull-request your changes over!

**Comment by andreasdc** [comment]
Is it fix safe? What does it do?

**Comment by CyberFlameGO** [comment]
#98
